##################################################################################################
# Booking service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: booking
    version: "1"
  name: booking
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: booking
    version: "1"
  type: LoadBalancer


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hc-booking-java-config
data:
    APPDYNAMICS_AGENT_APPLICATION_NAME: "Healthcare"
    APPDYNAMICS_AGENT_ACCOUNT_NAME: "APPD_ACCOUNT_NAME"
    APPDYNAMICS_CONTROLLER_HOST_NAME: "APPD_CONTROLLER_NAME.saas.appdynamics.com"
    APPDYNAMICS_CONTROLLER_PORT: "443"
    APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
    APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
    APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "bookingService"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
        version: "1"
    spec:
      containers:
      - name: booking
        command: ["/bin/sh"]
        args: ["-c", "java -javaagent:/opt/appdynamics/javaagent.jar -jar /bookingService-1.0.jar"]
        env:
        - name: DB_HOST
          value: jdbc:mysql://100.66.2.3:3306/healthcare
        - name: DB_USERNAME
          value: "db-user"
        - name: DB_PASSWORD
          value: "C1sco12345!"
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: bookingService
        envFrom:
        - configMapRef:
            name: hc-booking-java-config
        image: sgioia/fso-hc-booking_db:3
        imagePullPolicy: Always
        volumeMounts:
          - name: appd-agent-repo
            mountPath: /opt/appdynamics
        ports:
        - containerPort: 5001
      initContainers:
      - command:
        - cp
        - -r
        - /opt/appdynamics/.
        - /opt/temp
        name: appd-agent
        image: docker.io/appdynamics/java-agent:22.3.0
        volumeMounts:
        - name: appd-agent-repo
          mountPath: /opt/temp
      volumes:
        - name: appd-agent-repo
          emptyDir: {}


