##################################################################################################
# RoadRunner service
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadrunner-healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadrunner
  template:
    metadata:
      labels:
        app: roadrunner
        version: "1"
    spec:
      containers:
      - env:
        - name: TEST_URL
          value: "FRONTEND_HEALTHCARE_URL"
        - name: FRONTEND_HEALTHCARE_
          value: "80"
        name: roadrunner
        image: sgioia/fso-healthcare-roadrunner:6
        imagePullPolicy: Always

